# Generated by Django 3.2.7 on 2021-10-03 23:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_noticia', models.CharField(max_length=200)),
                ('texto_noticia', models.TextField()),
                ('data_noticia', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('foto_noticia', models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
