# Generated by Django 3.2.7 on 2021-10-21 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='categoria_noticia',
            field=models.CharField(default='tecnologia', max_length=200),
            preserve_default=False,
        ),
    ]
