# Generated by Django 3.2.7 on 2021-09-28 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pizza', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('categoria', models.CharField(max_length=100)),
                ('data_cadastro', models.DateField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
