# Generated by Django 3.2.7 on 2021-10-21 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presentation', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pizza',
        ),
    ]
